# Generated by Django 5.0 on 2023-12-20 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vHospitalName', models.CharField(max_length=255)),
                ('vCity', models.CharField(max_length=255)),
                ('vState', models.CharField(max_length=255)),
                ('vAddress', models.CharField(max_length=255)),
                ('eStatus', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalLogo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vLogoID', models.CharField(max_length=255)),
                ('dDateTime', models.DateTimeField()),
                ('vIP', models.CharField(max_length=255)),
                ('iLoginID', models.IntegerField()),
                ('dUDateTime', models.DateTimeField()),
                ('vUIP', models.CharField(max_length=255)),
                ('hmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hospitalmaster')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vZipFileName', models.CharField(max_length=255)),
                ('dDateTime', models.DateTimeField()),
                ('vIP', models.CharField(max_length=255)),
                ('iLoginID', models.IntegerField()),
                ('dUDateTime', models.DateTimeField()),
                ('vUIP', models.CharField(max_length=255)),
                ('hmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hospitalmaster')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalFacilities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vFileName', models.CharField(max_length=255)),
                ('dDateTime', models.DateTimeField()),
                ('vIP', models.CharField(max_length=255)),
                ('iLoginID', models.IntegerField()),
                ('dUDateTime', models.DateTimeField()),
                ('vUIP', models.CharField(max_length=255)),
                ('hmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hospitalmaster')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalDoctorProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vFileName', models.CharField(max_length=255)),
                ('dDateTime', models.DateTimeField()),
                ('vIP', models.CharField(max_length=255)),
                ('iLoginID', models.IntegerField()),
                ('dUDateTime', models.DateTimeField()),
                ('vUIP', models.CharField(max_length=255)),
                ('hmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hospitalmaster')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalAchievements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vFileName', models.CharField(max_length=255)),
                ('dDateTime', models.DateTimeField()),
                ('vIP', models.CharField(max_length=255)),
                ('iLoginID', models.IntegerField()),
                ('dUDateTime', models.DateTimeField()),
                ('vUIP', models.CharField(max_length=255)),
                ('hmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hospitalmaster')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalPatientAwarenessMaterials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vFileName', models.CharField(max_length=255)),
                ('dDateTime', models.DateTimeField()),
                ('vIP', models.CharField(max_length=255)),
                ('iLoginID', models.IntegerField()),
                ('dUDateTime', models.DateTimeField()),
                ('vUIP', models.CharField(max_length=255)),
                ('hmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hospitalmaster')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalSocialMediaLinks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vLinkedIn', models.CharField(max_length=255)),
                ('vTwitter', models.CharField(max_length=255)),
                ('vInstagram', models.CharField(max_length=255)),
                ('vFaceBook', models.CharField(max_length=255)),
                ('vYoutube', models.CharField(max_length=255)),
                ('vSocial1', models.CharField(max_length=255)),
                ('vSocial2', models.CharField(max_length=255)),
                ('dDateTime', models.DateTimeField()),
                ('vIP', models.CharField(max_length=255)),
                ('iLoginID', models.IntegerField()),
                ('dUDateTime', models.DateTimeField()),
                ('vUIP', models.CharField(max_length=255)),
                ('hmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hospitalmaster')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalTiming',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vFileName', models.CharField(max_length=255)),
                ('dDateTime', models.DateTimeField()),
                ('vIP', models.CharField(max_length=255)),
                ('iLoginID', models.IntegerField()),
                ('dUDateTime', models.DateTimeField()),
                ('vUIP', models.CharField(max_length=255)),
                ('hmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hospitalmaster')),
            ],
        ),
    ]
