# Generated by Django 3.2.10 on 2024-01-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalmaster',
            name='vURL',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
