# Generated by Django 3.2.10 on 2024-01-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hospitalmaster_vurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalmaster',
            name='eStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10, null=True),
        ),
    ]
