# Generated by Django 3.2.10 on 2024-01-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_hospitalmaster_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalmaster',
            name='eStatus',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
