# Generated by Django 3.2.10 on 2024-01-02 12:19

from django.db import migrations, models
import django.utils.timezone
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_hospitalimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalimages',
            name='dDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hospitalimages',
            name='dUDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hospitalimages',
            name='vZipFileName',
            field=models.FileField(blank=True, null=True, upload_to=home.models.get_upload_path),
        ),
    ]
