# Generated by Django 3.2.10 on 2024-01-02 13:02

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_hospitalimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.get_upload_path),
        ),
    ]
