# Generated by Django 3.2.10 on 2024-01-03 13:18

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_hospitallogo_vlogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalachievements',
            name='iLoginID',
        ),
        migrations.RemoveField(
            model_name='hospitaldoctorprofile',
            name='iLoginID',
        ),
        migrations.RemoveField(
            model_name='hospitalfacilities',
            name='iLoginID',
        ),
        migrations.RemoveField(
            model_name='hospitalpatientawarenessmaterials',
            name='iLoginID',
        ),
        migrations.RemoveField(
            model_name='hospitalsocialmedialinks',
            name='iLoginID',
        ),
        migrations.RemoveField(
            model_name='hospitaltiming',
            name='iLoginID',
        ),
        migrations.AlterField(
            model_name='hospitalpatientawarenessmaterials',
            name='vFileName',
            field=models.FileField(blank=True, null=True, upload_to=home.models.get_paMaterial_upload_path),
        ),
    ]
